### PR TITLE
enhancements to support multiple topics, generating indexes with ProgressMonitor support and reduced memory use

### PR DESCRIPTION
**Pull request by tobidelbruck**
This is a fairly major pull with things I had to do to support reading the large rosbags we use for playing back our large (>10GB) rosbags from robot experiments. A large memory leak is fixed by making collectsStats an optional flag for development. A new public method generateIndexForTopicList is added to generate a combined index for multiple topics. It includes support for canceling the operation via the progressMonitor you pass in. I also enhanced the MessageIndex to include the item topic and Timestamp for dealing with messages. We really need these enchancements for our project. A minor bug with checking the index for out of bounds to correctly generate ArrayIndexOutOfBounds exception is also fixed.

### CODE REVIEW

**Comment by pjreed** [comment]
Thanks, this looks good.  I don't have the time right at the moment, but I'll test this out in the near future and then merge it in.

**Comment by Explorer89** [comment]
@pjreed Could you please merge this change as this is really impacting using the library to process large rosbags

**Comment by tobidelbruck** [comment]
I made a jar from my fork and just included that static jar in our 
project. It seems to work ok even for files up to 12GB; initial parsing 
is slow but a cache file of the index speeds up subsequent opens to 
almost instantaneous. Please let me know. I guess this fork is accessible.

**Comment by tobidelbruck** [comment]
See https://github.com/tobidelbruck/bag-reader-java for my fork with the 
fixes to memory leak.  Also if you are interested, see 
https://github.com/SensorsINI/jaer/blob/ivy-bagreader/src/net/sf/jaer/eventio/ros/RosbagFileInputStream.java 
for use of this very useful BagReader. This implementation caches the 
index file for subsequent opens; see method maybeLoadCachdMsgIndexes.

**Comment by pjreed** [comment]
Sorry for taking so long to get around to this, I got distracted by other projects and completely forgot about it.  Thanks again!

**Pull request merged**
