### PR TITLE
Fix logic inversion when reading Booleans

### PR DESCRIPTION
**Pull request by lukehutch**
I was wondering why I was getting the wrong value from bagfiles for Booleans...

### CODE REVIEW

**Comment by pjreed** [comment]
Good catch, I thought I had added tests for all of the primitive data types, but it looks like I missed Booleans somehow.  Could you also add a unit test for it?

**Comment by lukehutch** [comment]
Apologies, I have a hectic schedule for the next few weeks, but I'll try to get to it after that if you haven't had a chance to.

**Comment by lukehutch** [comment]
BTW thank for open sourcing this! It saved me a lot of time.

**Comment by pjreed** [comment]
Sorry about forgetting about this for a while, but I went ahead and added a unit test and put it in the PR at #50, so I'll close this one.  Thanks for finding it!

**Comment by lukehutch** [comment]
Thanks!

**Pull request closed without merging**
